Python/源码/七月/StudyWerkzeug/app/main/forms.py
from flask_wtf import Form
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class loginForm(Form):
    username = StringField('用户名', validators=[DataRequired()])
    password = StringField('用户密码', validators=[DataRequired()])
    submit = SubmitField('提交')


class registForm(Form):
    email = StringField('邮箱', validators=[DataRequired()])
    username = StringField('用户名', validators=[DataRequired()])
    password = StringField('用户密码', validators=[DataRequired()])
    submit = SubmitField('提交')

Python/源码/七月/StudyWerkzeug/app/Dictionary/__init__.py
from flask import Blueprint

dictionary = Blueprint('dictionary',__name__)

from . import views

Python/源码/七月/StudyWerkzeug/app/Dictionary/views.py
from flask import render_template
from . import dictionary

@dictionary.route('/dictionary')
def index():
    return render_template('/dictionaryTemplates/index.html')

Python/源码/七月/StudyWerkzeug/app/__init__.py
from flask import Flask
from config import config
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager



bootStrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    config[config_name].init_app(app)
    bootStrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .manage import manage as manage_blueprint
    app.register_blueprint(manage_blueprint)

    from .Dictionary import dictionary as dictionary_blueprint
    app.register_blueprint(dictionary_blueprint)

    return app

Python/源码/七月/StudyWerkzeug/app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views

Python/源码/七月/StudyWerkzeug/app/main/views.py
from flask import render_template, url_for, flash
from . import main
from .mainModel import NavModel, indexModel, userModel
from .forms import loginForm, registForm
from .. import db
from flask_login import login_required,login_user,logout_user
from flask import redirect


# 一级界面 不需要登陆
@main.route('/')
def index():
    m = indexModel(indicators=['0', '1', '2'], imgSrc=['img/nav1.jpg',
                                                       'img/nav2.jpg',
                                                       'img/nav3.jpg'])
    return render_template('index.html', m=m)


@main.route('/bootstrap')
def bootstrap():
    v1 = NavModel(name='主页', element_id='zhuye', url='#zhuye')
    v2 = NavModel(name='a', element_id='a', url='#a')
    v3 = NavModel(name='b', element_id='b', url='#b')
    v4 = NavModel(name='c', element_id='b', url='#c')

    return render_template('bootstrap.html', list=[v1, v2, v3, v4])


@main.route('/JQuery')
def jquery():
    return render_template('JQuery.html')


@main.route('/login', methods=['GET', 'POST'])
def login():
    form = loginForm()
    if form.validate_on_submit():
        user = userModel.query.filter_by(name=form.username.data).first()
        if user is not None and user.verify_password(user.password_hash, form.password.data):
            flash('登陆成功')
            login_user(user)
            return redirect(url_for('main.index'))
    return render_template('login.html', form=form)


@main.route('/regist', methods=['GET', 'POST'])
def regist():
    form = registForm()
    if form.validate_on_submit():
        m = userModel(email=form.email.data,
                      name=form.username.data,
                      password=form.password.data)
        db.session.add(m)
        db.session.commit()
        flash(u'注册成功', 'message')
        return redirect(url_for('main.index'))
    return render_template('regist.html', form=form)

@main.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@main.route('/user')
def user():
    return render_template('main.html')


@main.route('/test')
def test():
    # return render_template('temp.html')
    return redirect(url_for('main.index'))

Python/源码/七月/StudyWerkzeug/app/templates/JQuery.html
{% extends "base.html" %}

{% block content%}
{{super()}}

{% endblock %}

Python/源码/七月/StudyWerkzeug/app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %} clb {% endblock %}

{% block head %}
    {{super()}}
<!--clb-->
    <script src="{{url_for('static',filename='Javastrap.js')}}"></script>
    <script>
        var str = "http://127.0.0.1:5000/static/styles.css?radom="+Math.random();
        var head = document.getElementsByTagName('head')[0],
        cssURL = str,
        linkTag = document.createElement('link');
        linkTag.id = 'dynamic-style';
        linkTag.href = cssURL;
        linkTag.setAttribute('rel','stylesheet');
//        linkTag.setAttribute('media','all');
        linkTag.setAttribute('type','text/css');
        head.appendChild(linkTag);
    </script>
{% block append %}{% endblock %}
{% endblock %}

{% block navbar%}
    <div class="container ">
        <div class="nav">
            <ul class="nav nav-pills nav-justified">
                <li class=""><a href="{{url_for('main.index')}}">home</a></li>
                <li><a href="#">Object-C</a></li>
                <li><a href="#">Python</a></li>
                <li><a href="{{url_for('dictionary.index')}}">词典</a></li>

                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        前端<span class="caret">
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#">HTML</a></li>
                        <li><a href="#">CSS</a></li>
                        <li><a href="#">JS</a></li>
                        <li class="divider"></li>
                        <li><a href="#">JQuery</a></li>
                        <li><a href="{{url_for('main.bootstrap')}}">Bootstrap</a></li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        用户<span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        {% if current_user.is_authenticated %}
                        <li><a href="{{url_for('main.logout')}}">退出登陆</a></li>
                        {% else %}
                        <li><a href="{{url_for('main.login')}}">登陆</a></li>
                        {% endif %}

                        <li><a href="{{url_for('main.regist')}}">注册</a></li>
                        {% if current_user.is_authenticated %}
                        <li class="divider"></li>
                        <li><a href="{{url_for('manage.manage')}}">管理</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
        </div>
    </div>
{% endblock %}

{% block content%}
   {% for message in get_flashed_messages()%}
     <div class="container">
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert">
                &times
            </button>
            {{message}}
        </div>
    </div>
    {% endfor%}

    <div class="clb_divider_height"></div>
    {%block page_content%}{%endblock%}
{% endblock %}

{%block scripts %}
    {{super()}}
{% endblock %}

Python/源码/七月/StudyWerkzeug/app/templates/bootstrap.html
{% extends "base.html" %}

{% block append %}
{{super()}}
    <style>

    </style>
{% endblock %}

{% block page_content%}
<div class="container col-lg-2">

    <ul id="myTabs" class="nav nav-pills nav-stacked"><!--role是标签扮演的角色属性，更多的是注明作用，对css样式没影响。可能对js事件有影响-->
        {% for i in list%}
        <li role="presentation"><a href={{i.url}}  data-toggle="tab">{{i.name}}</a></li>
        {% endfor %}
    </ul>

</div>

<div class="container col-lg-10">
    <div class="tab-content">
        {% for i in list %}
        <!--http://www.bjhee.com/jinja2-filter.html-->
        <div class="tab-pane fade " id = {{i.element_id}}><p>{{i.element_id}}</p></div>
        {% endfor%}

    </div>
</div>

{% endblock%}

Python/源码/七月/StudyWerkzeug/app/templates/index.html
{% extends "base.html" %}

{% block append %}


{% endblock %}

{% block page_content%}


    <div id="carousel" class="carousel slide " data-ride="carousel" data-interval = '10000' >
        <!--轮播标志-->
        <ol class="carousel-indicators">
            {% for i in m.indicators%}
                {% if i == '0' %}
                    <li data-slide-to='{{ i }}'  class="active"></li>
                {% else %}
                    <li data-slide-to="{{ i }}" ></li>
                {% endif %}
            {% endfor%}
        </ol>
        <!--轮播项目-->
        <div class="carousel-inner">
            {% for i in m.imgSrc %}
                {% if i == 'img/nav1.jpg' %}
                    <div class="item active">
                    <img src= " {{url_for('static', filename = i)}} " >
                    </div>
                {% else %}
                    <div class="item">
                        <img src= " {{url_for('static', filename = i)}} " >
                     </div>
                {% endif %}
            {% endfor %}
        </div>
        <!--轮播导航-->
        <a class="carousel-control left" href="#carousel" data-slide ='prev'>prew</a>
        <a class="carousel-control right" href="#carousel" data-slide="next">next</a>
    </div>



{% endblock %}

Python/源码/七月/StudyWerkzeug/app/templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
    <div class='col-md-4'>
    {{ wtf.quick_form(form) }}
    </div>
{% endblock%}

Python/源码/七月/StudyWerkzeug/app/templates/main.html
{% extends "base.html" %}


{% block content%}
{{super()}}
{% endblock %}

Python/源码/七月/StudyWerkzeug/app/templates/manage.html
{% extends "bootstrap/base.html" %}

{% block head %}
 {{super()}}
    <link rel="stylesheet" href="{{url_for('static',filename='thirdPart/custom.css')}}">
     <script>
        var str = "http://127.0.0.1:5000/static/thirdPart/manage.css?radom="+Math.random();
        var head = document.getElementsByTagName('head')[0],
        cssURL = str,
        linkTag = document.createElement('link');
        linkTag.id = 'dynamic-style';
        linkTag.href = cssURL;
        linkTag.setAttribute('rel','stylesheet');
//        linkTag.setAttribute('media','all');
        linkTag.setAttribute('type','text/css');
        head.appendChild(linkTag);
    </script>

{% endblock %}

{% block content %}
    <div class="main_container">
        <div class="col-md-2 col-xs-2 left_container">

                <ul class="menu-one">
                    <li><span class="caidan">菜单一</span>
                         <ul style="display: none">
                            <li><a href="{{url_for('manage.upload')}}">上传照片</a></li>
                            <li><a href="#">b</a></li>
                        </ul>
                    </li>
                    <li  ><span class="caidan">菜单二</span>
                         <ul style="display: none">
                            <li><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                        </ul>
                    </li>
                    <li  >
                        <span class="caidan">菜单三</span>
                        <ul style="display: none">
                            <li><a href="#">a1</a></li>
                            <li><a href="#">b2</a></li>
                        </ul>
                    </li>
                </ul>

        </div>
        <div class="col-md-10 col-xs-10 right_container test">
        </div>
    </div>

    <style>
        body {font-size: 20px;font-family: "宋体","微软雅黑";}
        a:link, a:visited{text-decoration: none}
        ul,li{list-style: none;}
        /* 所有li都设置颜色*/
        .menu-one {padding-left: 0px}
        .menu-one li{background-color: green;border: 1px #316a91; border-bottom: 0px}
        .menu-one li a{padding-left: 10px;}
        .menu-one li span{background-color:orange}
        /*.menu-one .caidans{background-color: #7FFFD4 }*/
        .menu-one li ul {display: none}

    </style>
{% endblock%}

{%block scripts %}
    {{super()}}
    <script>
        $(document).ready(function () {
            $('.caidan').click(function () {

                if($(this).siblings('ul').css('display') == 'none')
                {
                    $(this).siblings('ul').slideDown(100).children('li');

                }
                else
                {
                    $(this).siblings('ul').slideUp(100);
                }
            })
        });
    </script>

{% endblock %}

Python/源码/七月/StudyWerkzeug/app/templates/regist.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block page_content %}
    <div class='col-md-4'>
    {{ wtf.quick_form(form) }}
    </div>
{% endblock%}

Python/源码/七月/StudyWerkzeug/app/templates/temp.html
{% extends "bootstrap/base.html" %}


{% block content %}
            <div class="list">
                <ul class="yiji">
                    <li><a href="#">中国美协章程</a></li>
                    <li><a href="#" class="inactive active">中国文联美术艺术中心</a>
                        <ul style="display: none">
                            <li><a href="#">综合部</a></li>
                            <li><a href="#">大型活动部</a></li>
                            <li><a href="#">展览部</a></li>
                            <li><a href="#">艺委会工作部</a></li>
                            <li><a href="#">信息资源部</a></li>
                            <li><a href="#">双年展办公室</a></li>
                        </ul>
                    </li>
                    <li><a href="#" class="inactive">组织机构</a>
                        <ul style="display: none">
                            <li><a href="#" class="inactive active">美协机关</a>
                                <ul>
                                    <li><a href="#">办公室</a></li>
                                    <li><a href="#">人事处</a></li>
                                    <li><a href="#">组联部</a></li>
                                    <li><a href="#">外联部</a></li>
                                    <li><a href="#">研究部</a></li>
                                    <li><a href="#">维权办</a></li>
                                </ul>
                            </li>
                            <li><a href="#" class="inactive active">中国文联美术艺术中心</a>
                                <ul>
                                    <li><a href="#">综合部</a></li>
                                    <li><a href="#">大型活动部</a></li>
                                    <li><a href="#">展览部</a></li>
                                    <li><a href="#">艺委会工作部</a></li>
                                    <li><a href="#">信息资源部</a></li>
                                    <li><a href="#">双年展办公室</a></li>
                                </ul>
                            </li>
                            <li class="last"><a href="#">《美术》杂志社</a></li>
                        </ul>
                    </li>
                    <li><a href="#" class="inactive">组织机构</a>
                        <ul style="display: none">
                            <li><a href="#" class="inactive active">美协机关</a>
                                <ul>
                                    <li><a href="#">办公室</a></li>
                                    <li><a href="#">人事处</a></li>
                                    <li><a href="#">组联部</a></li>
                                    <li><a href="#">外联部</a></li>
                                    <li><a href="#">研究部</a></li>
                                    <li><a href="#">维权办</a></li>
                                </ul>
                            </li>
                            <li><a href="#" class="inactive active">中国文联美术艺术中心</a>
                                <ul>
                                    <li><a href="#">综合部</a></li>
                                    <li><a href="#">大型活动部</a></li>
                                    <li><a href="#">展览部</a></li>
                                    <li><a href="#">艺委会工作部</a></li>
                                    <li><a href="#">信息资源部</a></li>
                                    <li><a href="#">双年展办公室</a></li>
                                </ul>
                            </li>
                            <li class="last"><a href="#">《美术》杂志社</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>


     <style type="text/css">
    *{margin: 0;padding: 0}
    body .list{font-size: 12px;font-family: "宋体","微软雅黑";}
    ul,li{list-style: none;}
    a:link,a:visited{text-decoration: none;color: #fff;}
    .list{width: 210px;border-bottom:solid 1px #316a91;margin:40px auto 0 auto;}
    .list ul li{background-color:#467ca2; border:solid 1px red; border-bottom:0;}
    .list ul li a{padding-left: 10px;color: #fff; font-size:12px; display: block; font-weight:bold; height:36px;line-height: 36px;position: relative;
    }
    .list ul li .inactive{ background:url(images/off.png) no-repeat 184px center;}
    .list ul li .inactives{background:url(images/on.png) no-repeat 184px center;}
    .list ul li ul{display: none;}
    .list ul li ul li { border-left:0; border-right:0; background-color:#6196bb; border-color:#467ca2;}
    .list ul li ul li ul{display: none;}
    .list ul li ul li a{ padding-left:20px;}
    .list ul li ul li ul li { background-color:#d6e6f1; border-color:#6196bb; }
    .last{ background-color:#d6e6f1; border-color:#6196bb; }
    .list ul li ul li ul li a{ color:#316a91; padding-left:30px;}
    </style>

    <script>
        $(document).ready(function() {
        $('.inactive').click(function(){
            if($(this).siblings('ul').css('display')=='none'){
                $(this).addClass('inactives');
                $(this).siblings('ul').slideDown(100).children('li');
            }else{
                $(this).removeClass('inactives');
                $(this).siblings('ul').slideUp(100);
            }
            alert('haha:'+$(this).html())
        })
    });
    </script>
{% endblock%}

Python/源码/七月/StudyWerkzeug/app/templates/upload_file.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
    <div class='col-md-4'>
        {{ wtf.quick_form(form) }}
    </div>
{% endblock%}